spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sport_tracker
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api 